In [69]:
import numpy as np
from sklearn.metrics import *

kevin = np.array(
        [[1044,  417,  233,   12,    0],
         [  17,   18,   19,    2,    0],
         [  81,  106,  467,   57,    0],
         [   5,   11,   75,  378,   17],
         [   0,    0,    0,    8,   83],]).astype(float)

suhas = np.array(
        [[ 597,  132,   32,    0,    0],
         [ 161,  115,   78,    2,    0],
         [  43,   86,  304,   24,    0],
         [   4,    1,   44,  206,    6],
         [   0,    0,    0,    7,   45],]).astype(float)

np.sum(kevin)
np.sum(suhas)

1887.0

In [67]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

def precisions_from_cm(cm):
    return np.diag(cm) / np.sum(cm,1)

def recalls_from_cm(cm):
    return np.diag(cm) / np.sum(cm,0)

def accuracy_from_cm(cm):
    return sum(np.diag(cm)) / np.sum(cm)

def f1s_from_cm(cm):
    p = precisions_from_cm(cm)
    r = recalls_from_cm(cm)
    return 2 * p * r / (p + r)

def metrics_from_cm(cm):
    a = accuracy_from_cm(cm)
    p = precisions_from_cm(cm)
    r = recalls_from_cm(cm)
    f1 = f1s_from_cm(cm)
    return p,r,f1,a
    
def print_metrics(metrics):
    print("Precision (mean=%.2f)" % np.mean(metrics[0]))
    print(metrics[0])
    print("Recall (mean=%.2f)" % np.mean(metrics[1]))
    print(metrics[1])
    print("F1 (mean=%.2f)" % np.mean(metrics[2]))
    print(metrics[2])
    print("Overall accuracy")
    print(metrics[3])
    pass

print("** DenseNet **")
print_metrics(metrics_from_cm(kevin))
print("\n** Faster R-CNN **")
print_metrics(metrics_from_cm(suhas))

** DenseNet **
Precision (mean=0.66)
[0.61 0.32 0.66 0.78 0.91]
Recall (mean=0.64)
[0.91 0.03 0.59 0.83 0.83]
F1 (mean=0.62)
[0.73 0.06 0.62 0.80 0.87]
Overall accuracy
0.6524590163934426

** Faster R-CNN **
Precision (mean=0.69)
[0.78 0.32 0.67 0.79 0.87]
Recall (mean=0.70)
[0.74 0.34 0.66 0.86 0.88]
F1 (mean=0.69)
[0.76 0.33 0.66 0.82 0.87]
Overall accuracy
0.6714361420243773
